"""Remove notepad module

Revision ID: 908b07421a63
Revises: fdb15703b714
Create Date: 2025-12-08 13:27:43.147570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '908b07421a63'
down_revision = 'fdb15703b714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notepad')
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_set_dataset_kind'), ['dataset_kind'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_set_dataset_kind'))

    op.create_table('notepad',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('body', mysql.TEXT(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('notepad_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('trending')
    # ### end Alembic commands ###
