"""Rename uvl_filename to filename and uvl_version to file_version in fm_meta_data

Revision ID: e22ad4186291
Revises: b03656ce4e61
Create Date: 2025-11-04 11:32:45.794603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e22ad4186291'
down_revision = 'b03656ce4e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # MySQL requiere especificar el tipo al renombrar columnas
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        # Renombrar uvl_filename a filename (tipo String(120), NOT NULL)
        batch_op.alter_column('uvl_filename',
                              new_column_name='filename',
                              existing_type=sa.String(length=120),
                              nullable=False)
        
        # Renombrar uvl_version a file_version (tipo String(120), nullable)
        batch_op.alter_column('uvl_version',
                              new_column_name='file_version',
                              existing_type=sa.String(length=120),
                              nullable=True)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('fm_meta_data', schema=None) as batch_op:
        # Revertir: filename a uvl_filename
        batch_op.alter_column('filename',
                              new_column_name='uvl_filename',
                              existing_type=sa.String(length=120),
                              nullable=False)
        
        # Revertir: file_version a uvl_version
        batch_op.alter_column('file_version',
                              new_column_name='uvl_version',
                              existing_type=sa.String(length=120),
                              nullable=True)
    
    # ### end Alembic commands ###
